version: "3"
services:
  lib:
    image: keonwoo/cs492c:test
    environment:
      NODE_ENV: test
    command: bash -c 'yarn set version 3.1.0 && yarn install && yarn plugin import workspace-tools && yarn workspace @team-10/lib run test:workflow'
    volumes:
      - ./.yarn/:/app/.yarn/
      - ./packages/lib/:/app/packages/lib/
      - ./coverage/:/app/coverage/:Z
  backend:
    image: keonwoo/cs492c:test
    environment:
      NODE_ENV: test
    command: bash -c 'yarn set version 3.1.0 && yarn install && yarn plugin import workspace-tools && yarn workspace @team-10/backend run test:workflow'
    volumes:
      - ./.yarn/:/app/.yarn/
      - ./packages/lib/:/app/packages/lib/
      - ./packages/backend/:/app/packages/backend/
      - ./coverage/:/app/coverage/:Z
  frontend:
    image: keonwoo/cs492c:test
    environment:
      NODE_ENV: test
    command: bash -c 'yarn set version 3.1.0 && yarn install && yarn plugin import workspace-tools && yarn workspace @team-10/frontend run test:workflow'
    volumes:
      - ./.yarn/:/app/.yarn/
      - ./packages/lib/:/app/packages/lib/
      - ./packages/frontend/:/app/packages/frontend/
      - ./coverage/:/app/coverage/:Z
