name: test@node-14.18.1

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: docker-compose -f "docker-compose.workflow.yml" build

      - name: Run yarn install
        run: yarn install

      - name: Run lint-staged
        run: yarn lint-staged

      - name: Add and commit if any changes happened
        uses: EndBug/add-and-commit@v7
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          add: 'packages'

          # The name of the user that will be displayed as the author of the commit.
          author_name: ESLint (GitHub Workflows)

          # The message for the commit.
          message: 'Commit from Linter'

      - name: Test lib
        run: docker-compose -f "docker-compose.workflow.yml" up --exit-code-from lib lib

      - name: Test backend
        run: docker-compose -f "docker-compose.workflow.yml" up --exit-code-from backend backend

      - name: Test frontend
        run: docker-compose -f "docker-compose.workflow.yml" up --exit-code-from frontend frontend

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.workflow.yml" down
