name: test@node-14.18.1

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  node:
    timeout-minutes: 30
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run yarn install
        run: yarn install

      - name: Run lint-staged
        run: yarn lint-staged

      - name: Add and commit if any changes happened
        uses: EndBug/add-and-commit@v7
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          add: 'packages'

          # The name of the user that will be displayed as the author of the commit.
          author_name: ESLint (GitHub Workflows)

          # The message for the commit.
          message: 'Commit from Linter'

      - name: Check coverage existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "coverage"

      - name: Upload coverage to Codecov
        if: steps.check_files.outputs.files_exists == 'true'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
